package com.temenos.multiinstanceexample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "FirstName")
	private java.lang.String firstname;
	@org.kie.api.definition.type.Label(value = "LastName")
	private java.lang.String lastname;
	@org.kie.api.definition.type.Label(value = "age")
	private java.lang.Integer age;

	public Employee() {
	}

	public java.lang.String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(java.lang.String firstname) {
		this.firstname = firstname;
	}

	public java.lang.String getLastname() {
		return this.lastname;
	}

	public void setLastname(java.lang.String lastname) {
		this.lastname = lastname;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public Employee(java.lang.String firstname, java.lang.String lastname,
			java.lang.Integer age) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.age = age;
	}

}